name: Generate PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Puppeteer
        run: npm install puppeteer
        
      - name: Create PDF conversion script
        run: |
          cat > convert.js <<'EOL'
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          const path = require('path');

          (async () => {
            const browser = await puppeteer.launch({
              headless: 'new',
              args: ['--no-sandbox']
            });
            const page = await browser.newPage();
            
            // Read the HTML file
            const htmlPath = path.join(process.cwd(), 'index.html');
            const html = fs.readFileSync(htmlPath, 'utf8');
            
            await page.setContent(html, { waitUntil: 'networkidle0' });
            
            // Generate PDF
            await page.pdf({
              path: 'home-automation-systems-comparison.pdf',
              format: 'A4',
              printBackground: true,
              margin: {
                top: '20px',
                right: '20px',
                bottom: '20px',
                left: '20px'
              }
            });
            
            await browser.close();
            console.log('PDF created successfully!');
          })();
          EOL
          
      - name: Convert HTML to PDF
        run: node convert.js
        
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: home-automation-systems-comparison
          path: home-automation-systems-comparison.pdf
          
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add home-automation-systems-comparison.pdf
          git commit -m "Generate PDF from HTML" || echo "No changes to commit"
          git push